pipeline {
  agent any

  environment {
    REPO_GIT = 'https://github.com/concafrastech/alegria_api.git'
  }

  stages {
    stage('Checkout SCM') {
      steps {
        // git branch: 'main'
        //     credentialsId: 'viniciusks_github'
        //     url: "${REPO_GIT}"

        checkout scm

        sh 'pwd'
        sh 'ls -la'
      }
    }
    stage('Segundo Stage') {
      steps {
        echo 'Step 1. Hello World'
        echo 'Step 2. Hello Brazil'
      }
    }
  }
}
