pipeline {
  agent any

  environment {
    REPO_GIT = 'https://github.com/concafrastech/alegria_api.git'
  }

  stages {
    stage('Check Environment') {
      steps {
        sh 'pwd'
        sh 'ls -la'
      }
    }
    stage('Build Image Docker') {
      steps {
        echo 'Step 1. Hello World'
        echo 'Step 2. Hello Brazil'
      }
    }
  }
}
