pipeline {
  agent any

  environment {
    REPO_GIT = 'https://github.com/concafrastech/alegria_api.git'
  }

  stages {
    stage('Check Environment') {
      steps {
        sh 'pwd'
        sh 'ls -la'
      }
    }
    stage('Build Image Docker') {
      steps {
        echo '..:: Iniciando a compilacao da imagem spring-boot Docker ::..'
        withMaven {
          sh 'cd .. && mvn spring-boot:build-image'
        }
      }
    }
  }
}
